//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessAnotherMaket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participants
    {
        public int Id { get; set; }
        public Nullable<int> Users_id { get; set; }
        public Nullable<int> Conseravtion_id { get; set; }
        public Nullable<int> Type_id { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Razgovor Razgovor { get; set; }
        public virtual Users Users { get; set; }
    }
}
