//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessAnotherMaket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Contact
    {
        public int Id { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> Contact_id { get; set; }
        public string Login { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public Nullable<System.DateTime> Deleted_at { get; set; }
    
        public virtual Contacts Contacts { get; set; }
        public virtual Users Users { get; set; }
    }
}
