//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessAnotherMaket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vlozhenia
    {
        public int Id { get; set; }
        public string Thumb_Url { get; set; }
        public string File_url { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public Nullable<System.DateTime> Deleted_at { get; set; }
        public Nullable<int> Messages_id { get; set; }
    
        public virtual Messages Messages { get; set; }
    }
}
